//  Service → Simple Icons slug map
// Keys are lowercase-normalised (no spaces / punctuation).
// Values are the exact Simple Icons slug (see https://simpleicons.org).

export const SERVICE_SLUG_MAP: Record<string, string> = {
	// Streaming / Video 
	netflix:          "netflix",
	disneyplus:       "disneyplus",
	disney:           "disneyplus",
	hbomax:           "hbo",
	hbo:              "hbo",
	max:              "hbo",
	hulu:             "hulu",
	primevideo:       "primevideo",
	amazonprime:      "primevideo",
	amazon:           "amazon",
	appletv:          "appletv",
	peacock:          "peacock",
	paramountplus:    "paramount",
	crunchyroll:      "crunchyroll",
	twitch:           "twitch",
	youtube:          "youtube",
	youtubepremium:   "youtube",
	vimeo:            "vimeo",
	plex:             "plex",

	// Music / Audio 
	spotify:          "spotify",
	applemusic:       "applemusic",
	tidal:            "tidal",
	deezer:           "deezer",
	soundcloud:       "soundcloud",
	amazonmusic:      "amazonmusic",
	youtubemusic:     "youtubemusic",
	audible:          "audible",
	pandora:          "pandora",

	// AI / LLM 
	chatgpt:          "openai",
	openai:           "openai",
	claude:           "anthropic",
	anthropic:        "anthropic",
	gemini:           "googlegemini",
	googlegem:        "googlegemini",
	midjourney:       "midjourney",
	perplexity:       "perplexity",
	githubcopilot:    "githubcopilot",
	copilot:          "githubcopilot",
	grammarly:        "grammarly",
	jasper:           "jasper",
	elevenlabs:       "elevenlabs",
	cursor:           "cursor",
	grok:             "xai",

	// Developer Tools 
	github:           "github",
	gitlab:           "gitlab",
	bitbucket:        "bitbucket",
	jira:             "jira",
	confluence:       "confluence",
	atlassian:        "atlassian",
	linear:           "linear",
	vercel:           "vercel",
	netlify:          "netlify",
	heroku:           "heroku",
	digitalocean:     "digitalocean",
	render:           "render",
	sentry:           "sentry",
	datadog:          "datadog",
	postman:          "postman",
	supabase:         "supabase",
	planetscale:      "planetscale",

	// Cloud / Storage 	
	aws:              "amazonwebservices",
	googlecloud:      "googlecloud",
	gcp:              "googlecloud",
	azure:            "microsoftazure",
	microsoft:        "microsoft",
	office365:        "microsoftoffice",
	microsoftoffice:  "microsoftoffice",
	dropbox:          "dropbox",
	googledrive:      "googledrive",
	icloud:           "icloud",
	onedrive:         "microsoftonedrive",
	box:              "box",

	// Design / Creative
	figma:            "figma",
	sketch:           "sketch",
	adobe:            "adobe",
	adobecc:          "adobecreativecloud",
	creativecloud:    "adobecreativecloud",
	canva:            "canva",
	framer:           "framer",
	invision:         "invision",
	lottiefiles:      "lottiefiles",

	// Productivity / Notes 
	notion:           "notion",
	evernote:         "evernote",
	obsidian:         "obsidian",
	todoist:          "todoist",
	asana:            "asana",
	trello:           "trello",
	monday:           "monday",
	clickup:          "clickup",
	airtable:         "airtable",
	slack:            "slack",
	discord:          "discord",
	zoom:             "zoom",
	miro:             "miro",
	loom:             "loom",
	calendly:         "calendly",
	webex:            "ciscowebex",
	microsoftteams:   "microsoftteams",
	teams:            "microsoftteams",

	// Social / Writing 
	twitter:          "x",
	x:                "x",
	instagram:        "instagram",
	facebook:         "facebook",
	linkedin:         "linkedin",
	snapchat:         "snapchat",
	telegram:         "telegram",
	whatsapp:         "whatsapp",
	signal:           "signal",
	substack:         "substack",
	medium:           "medium",
	ghost:            "ghost",

	// Finance / Payments
	stripe:           "stripe",
	paypal:           "paypal",
	shopify:          "shopify",
	quickbooks:       "quickbooks",
	xero:             "xero",

	// Security / VPN / Privacy
	onepassword:      "1password",
	lastpass:         "lastpass",
	dashlane:         "dashlane",
	bitwarden:        "bitwarden",
	nordvpn:          "nordvpn",
	expressvpn:       "expressvpn",
	mullvad:          "mullvad",
	protonvpn:        "protonvpn",
	protonmail:       "proton",
	proton:           "proton",

	// Learning / Education
	coursera:         "coursera",
	udemy:            "udemy",
	pluralsight:      "pluralsight",
	skillshare:       "skillshare",
	duolingo:         "duolingo",
	brilliant:        "brilliant",
	readwise:         "readwise",
	leetcode:         "leetcode",

	// Analytics / Marketing 	
	posthog:          "posthog",
	mixpanel:         "mixpanel",
	hotjar:           "hotjar",
	mailchimp:        "mailchimp",
	hubspot:          "hubspot",
	intercom:         "intercom",
	zendesk:          "zendesk",

	// Health / Fitness
	strava:           "strava",
	peloton:          "peloton",
	headspace:        "headspace",
	calm:             "calm",

	// Gaming
	steam:            "steam",
	xbox:             "xbox",
	playstation:      "playstation",
	nintendo:         "nintendo",
	epicgames:        "epicgames",

	// Other SaaS 
	zapier:           "zapier",
	webflow:          "webflow",
	typeform:         "typeform",
	algolia:          "algolia",
	twilio:           "twilio",
	sendgrid:         "twilio",
};

export const SERVICE_DOMAIN_MAP: Record<string, string> = {
	netflix:          "netflix.com",
	disneyplus:       "disneyplus.com",
	disney:           "disneyplus.com",
	hbomax:           "hbo.com",
	hbo:              "hbo.com",
	max:              "hbo.com",
	hulu:             "hulu.com",
	primevideo:       "primevideo.com",
	amazonprime:      "amazon.com",
	amazon:           "amazon.com",
	appletv:          "apple.com",
	peacock:          "peacocktv.com",
	paramountplus:    "paramountplus.com",
	crunchyroll:      "crunchyroll.com",
	twitch:           "twitch.tv",
	youtube:          "youtube.com",
	youtubepremium:   "youtube.com",
	vimeo:            "vimeo.com",
	plex:             "plex.tv",

	// Music / Audio 
	spotify:          "spotify.com",
	applemusic:       "music.apple.com",
	tidal:            "tidal.com",
	deezer:           "deezer.com",
	soundcloud:       "soundcloud.com",
	amazonmusic:      "music.amazon.com",
	youtubemusic:     "music.youtube.com",
	audible:          "audible.com",
	pandora:          "pandora.com",

	// AI / LLM 
	chatgpt:          "openai.com",
	openai:           "openai.com",
	claude:           "anthropic.com",
	anthropic:        "anthropic.com",
	gemini:           "gemini.google.com",
	googlegem:        "gemini.google.com",
	midjourney:       "midjourney.com",
	perplexity:       "perplexity.ai",
	githubcopilot:    "github.com",
	copilot:          "github.com",
	grammarly:        "grammarly.com",
	jasper:           "jasper.ai",
	elevenlabs:       "elevenlabs.io",
	cursor:           "cursor.com",
	grok:             "x.ai",

	// Developer Tools 
	github:           "github.com",
	gitlab:           "gitlab.com",
	bitbucket:        "bitbucket.org",
	jira:             "atlassian.com",
	confluence:       "atlassian.com",
	atlassian:        "atlassian.com",
	linear:           "linear.app",
	vercel:           "vercel.com",
	netlify:          "netlify.com",
	heroku:           "heroku.com",
	digitalocean:     "digitalocean.com",
	render:           "render.com",
	sentry:           "sentry.io",
	datadog:          "datadoghq.com",
	postman:          "postman.com",
	supabase:         "supabase.com",
	planetscale:      "planetscale.com",

	// Cloud / Storage 	
	aws:              "aws.amazon.com",
	googlecloud:      "cloud.google.com",
	gcp:              "cloud.google.com",
	azure:            "azure.microsoft.com",
	microsoft:        "microsoft.com",
	office365:        "office.com",
	microsoftoffice:  "office.com",
	dropbox:          "dropbox.com",
	googledrive:      "drive.google.com",
	icloud:           "icloud.com",
	onedrive:         "onedrive.live.com",
	box:              "box.com",

	// Design / Creative
	figma:            "figma.com",
	sketch:           "sketch.com",
	adobe:            "adobe.com",
	adobecc:          "adobe.com",
	creativecloud:    "adobe.com",
	canva:            "canva.com",
	framer:           "framer.com",
	invision:         "invisionapp.com",
	lottiefiles:      "lottiefiles.com",

	// Productivity / Notes 
	notion:           "notion.so",
	evernote:         "evernote.com",
	obsidian:         "obsidian.md",
	todoist:          "todoist.com",
	asana:            "asana.com",
	trello:           "trello.com",
	monday:           "monday.com",
	clickup:          "clickup.com",
	airtable:         "airtable.com",
	slack:            "slack.com",
	discord:          "discord.com",
	zoom:             "zoom.us",
	miro:             "miro.com",
	loom:             "loom.com",
	calendly:         "calendly.com",
	webex:            "webex.com",
	microsoftteams:   "microsoft.com",
	teams:            "microsoft.com",

	// Social / Writing 
	twitter:          "x.com",
	x:                "x.com",
	instagram:        "instagram.com",
	facebook:         "facebook.com",
	linkedin:         "linkedin.com",
	snapchat:         "snapchat.com",
	telegram:         "telegram.org",
	whatsapp:         "whatsapp.com",
	signal:           "signal.org",
	substack:         "substack.com",
	medium:           "medium.com",
	ghost:            "ghost.org",

	// Finance / Payments
	stripe:           "stripe.com",
	paypal:           "paypal.com",
	shopify:          "shopify.com",
	quickbooks:       "quickbooks.intuit.com",
	xero:             "xero.com",

	// Security / VPN / Privacy
	onepassword:      "1password.com",
	lastpass:         "lastpass.com",
	dashlane:         "dashlane.com",
	bitwarden:        "bitwarden.com",
	nordvpn:          "nordvpn.com",
	expressvpn:       "expressvpn.com",
	mullvad:          "mullvad.net",
	protonvpn:        "protonvpn.com",
	protonmail:       "proton.me",
	proton:           "proton.me",

	// Learning / Education
	coursera:         "coursera.org",
	udemy:            "udemy.com",
	pluralsight:      "pluralsight.com",
	skillshare:       "skillshare.com",
	duolingo:         "duolingo.com",
	brilliant:        "brilliant.org",
	readwise:         "readwise.io",
	leetcode:         "leetcode.com",

	// Analytics / Marketing 	
	posthog:          "posthog.com",
	mixpanel:         "mixpanel.com",
	hotjar:           "hotjar.com",
	mailchimp:        "mailchimp.com",
	hubspot:          "hubspot.com",
	intercom:         "intercom.com",
	zendesk:          "zendesk.com",

	// Health / Fitness
	strava:           "strava.com",
	peloton:          "onepeloton.com",
	headspace:        "headspace.com",
	calm:             "calm.com",

	// Gaming
	steam:            "steampowered.com",
	xbox:             "xbox.com",
	playstation:      "playstation.com",
	nintendo:         "nintendo.com",
	epicgames:        "epicgames.com",

	// Other SaaS 
	zapier:           "zapier.com",
	webflow:          "webflow.com",
	typeform:         "typeform.com",
	algolia:          "algolia.com",
	twilio:           "twilio.com",
	sendgrid:         "sendgrid.com",
};

export const POPULAR_SERVICES_DATA: PopularServiceData[] = [
	{ key: "netflix",    label: "Netflix",      logoQuery: "Netflix",           keywords: ["netflix"] },
	{ key: "youtube",    label: "YouTube",      logoQuery: "YouTube",           keywords: ["youtube", "yt", "youtube premium"] },
	{ key: "spotify",    label: "Spotify",      logoQuery: "Spotify",           localIconKey: "spotify",  keywords: ["spotify"] },
	{ key: "disney",     label: "Disney+",      logoQuery: "Disney+",           keywords: ["disney", "disneyplus"] },
	{ key: "hbo",        label: "Max / HBO",    logoQuery: "Max / HBO",         keywords: ["hbo", "max", "hbomax"] },
	{ key: "hulu",       label: "Hulu",         logoQuery: "Hulu",              keywords: ["hulu"] },
	{ key: "appletv",    label: "Apple TV+",    logoQuery: "Apple TV+",         keywords: ["appletv", "apple tv"] },
	{ key: "primevideo", label: "Prime Video",  logoQuery: "Prime Video",       keywords: ["prime", "primevideo", "amazon prime"] },
	{ key: "chatgpt",    label: "ChatGPT",      logoQuery: "ChatGPT",           localIconKey: "openai",   keywords: ["openai", "chatgpt", "gpt"] },
	{ key: "claude",     label: "Claude",       logoQuery: "Claude",            localIconKey: "claude",   keywords: ["claude", "anthropic"] },
	{ key: "gemini",     label: "Gemini",       logoQuery: "Gemini",            keywords: ["gemini", "google ai"] },
	{ key: "midjourney", label: "Midjourney",   logoQuery: "Midjourney",        keywords: ["midjourney", "mj"] },
	{ key: "cursor",     label: "Cursor",       logoQuery: "Cursor",            keywords: ["cursor"] },
	{ key: "perplexity", label: "Perplexity",   logoQuery: "Perplexity",        keywords: ["perplexity"] },
	{ key: "github",     label: "GitHub",       logoQuery: "GitHub",            localIconKey: "github",   keywords: ["github", "copilot", "gh"] },
	{ key: "notion",     label: "Notion",       logoQuery: "Notion",            localIconKey: "notion",   keywords: ["notion"] },
	{ key: "figma",      label: "Figma",        logoQuery: "Figma",             localIconKey: "figma",    keywords: ["figma"] },
	{ key: "adobe",      label: "Adobe CC",     logoQuery: "Adobe CC",          localIconKey: "adobe",    keywords: ["adobe", "creative cloud", "photoshop", "illustrator"] },
	{ key: "canva",      label: "Canva",        logoQuery: "Canva",             localIconKey: "canva",    keywords: ["canva"] },
	{ key: "slack",      label: "Slack",        logoQuery: "Slack",             keywords: ["slack"] },
	{ key: "discord",    label: "Discord",      logoQuery: "Discord",           keywords: ["discord"] },
	{ key: "zoom",       label: "Zoom",         logoQuery: "Zoom",              keywords: ["zoom"] },
	{ key: "linear",     label: "Linear",       logoQuery: "Linear",            keywords: ["linear"] },
	{ key: "vercel",     label: "Vercel",       logoQuery: "Vercel",            keywords: ["vercel"] },
	{ key: "dropbox",    label: "Dropbox",      logoQuery: "Dropbox",           localIconKey: "dropbox",  keywords: ["dropbox"] },
	{ key: "nordvpn",    label: "NordVPN",      logoQuery: "NordVPN",           keywords: ["nordvpn", "vpn", "nord"] },
	{ key: "1password",  label: "1Password",    logoQuery: "1Password",         keywords: ["1password", "onepassword"] },
	{ key: "duolingo",   label: "Duolingo",     logoQuery: "Duolingo",          keywords: ["duolingo"] },
	{ key: "medium",     label: "Medium",       logoQuery: "Medium",            localIconKey: "medium",   keywords: ["medium", "substack"] },
	{ key: "strava",     label: "Strava",       logoQuery: "Strava",            keywords: ["strava"] },
	{ key: "other",      label: "Other",        simpleIconSlug: "helpdesk",     localIconKey: "plus",     keywords: [] },
];
